import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar/index'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import Dashboard from './Dashboard'
import Analytics from './Analytics'
import Invoice from './Invoice'
import Schedule from './Schedule'
import Calendar from './Calendar'
import Messages from './Messages'
import Notifications from './Notifications'
import Settings from './Settings'

const Home: NextPage = () => {
  const [activeTab, setActiveTab] = React.useState("Dashboard");
  const darkTheme = createTheme({
    palette: {
      primary: {
        main: '#442C2E',
        light: '#FEEAE6',
        dark: '#FEDBD0'
      },
      secondary: {
        main: '#FFFBFA',
        light: '#FEDBD0'
      }
    },
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <main className={styles.main}>
          <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />
          {activeTab == 'Dashboard' && <Dashboard />}
          {activeTab == 'Analytics' && <Analytics />}
          {activeTab == 'Invoice' && <Invoice />}
          {activeTab == "Schedule" && <Schedule />}
          {activeTab == 'Calendar' && <Calendar />}
          {activeTab == "Messages" && <Messages />}
          {activeTab == "Notifications" && <Notifications />}
          {activeTab == "Settings" && <Settings />}
        </main>
      </ThemeProvider>
    </div>
  )
}

export default Home
